# Again, sourced from:
# https://github.com/ros-planning/moveit2/blob/main/.github/workflows/format.yaml
# Thank you to moveit for the source code

name: Formatting (pre-commit)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format-12
      run: sudo apt-get install clang-format-12
    - uses: pre-commit/action@v2.0.3
      id: precommit
    - name: Upload pre-commit changes
      if: failure() && steps.precommit.outcome == 'failure'
      uses: rhaschke/upload-git-patch-action@main
      with:
        name: pre-commit
